language: "node_js"
node_js:
  - "6"
addons:
  apt:
    sources:
    - ppa:adilson/golang
    packages:
    - etcd
before_install:
  - "service etcd start"
install:
  - "npm install"
script:
  - "npm test"